### ISSUE TITLE
error adding decoy networks

### ISSUE THREAD

**Issue by Motasembt** [pmbento/karmadetector#1]
this problem happen when i click start  scan 
i have samsung s3 gt-i9300 / android 4.3

**Comment by pmbento** [comment]
Can you please confirm that WiFi is ON? The app always tries to enable it also.

Are you compiling from the repository or using the release version (https://github.com/pmbento/karmadetector/releases/download/v0.1/karmadetector-v0.1.apk)? If you're compiling, can you uncomment the LOG entries from "WifiScannerService.java" and give it a run? If not, I can send you a debug enabled version.

Thanks for the feedback.

**Comment by Motasembt** [comment]
yes wifi is on and i use the release version

**Comment by pmbento** [comment]
Just added a debug version here: https://github.com/pmbento/karmadetector/releases/download/v0.1/karmadetector-debug-v0.1.apk.zip

Can you please test it and send me the outputs?

**Comment by Motasembt** [comment]
i cant download the file ! 
will u please use uptobox.com to upload it and give me link  ?

**Comment by pmbento** [comment]
Sure. Uploaded here: https://www.dropbox.com/s/irv9aqrbewqrkgf/karmadetector-debug-v0.1.apk?dl=0

**Comment by Motasembt** [comment]
How can i send u the output

**Comment by pmbento** [comment]
Sorry, the app still doesn't have a feature to send logs, so please paste some screenshots here.

**Comment by pmbento** [comment]
@Motasembt did you had a chance to test and see the debug info?
